#!/sbin/busybox sh

/sbin/busybox mount -t rootfs -o remount,rw rootfs

start adbd
stop tvout

/sbin/busybox rm /cache
/sbin/busybox mkdir /cache
/sbin/busybox chmod 777 /cache
/sbin/busybox mount -t ext4 /dev/block/mmcblk0p7 /cache

/sbin/recovery
